branches:
  except:
    - /libpng[0-1][0-7]/

language: c

os:
  - freebsd
  - linux
  - osx

compiler:
  - clang
  - gcc

env:
  - AUTOMATION=cmake CI_NO_TEST=1
  - AUTOMATION=cmake CI_CMAKE_VARS="-DPNG_HARDWARE_OPTIMIZATIONS=ON" CI_SANITIZERS="address,undefined"
  - AUTOMATION=cmake CI_CMAKE_VARS="-DPNG_HARDWARE_OPTIMIZATIONS=OFF" CI_SANITIZERS="address,undefined"
  - AUTOMATION=configure CI_NO_TEST=1
  - AUTOMATION=configure CI_CONFIGURE_FLAGS="--enable-hardware-optimizations"
  - AUTOMATION=configure CI_CONFIGURE_FLAGS="--disable-hardware-optimizations"
  - AUTOMATION=makefiles CI_NO_TEST=1
  - AUTOMATION=makefiles CI_SANITIZERS="address,undefined"

matrix:
  include:
    - os: osx
      compiler: cc
      env: AUTOMATION=cmake CI_CMAKE_GENERATOR=Xcode
  exclude:
    - os: freebsd
      compiler: gcc
    - os: osx
      compiler: gcc

before_script:
  - 'export CI_CMAKE_BUILD_FLAGS="--parallel 2"'
  - 'export CI_CTEST_FLAGS="--parallel 2"'
  - 'export CI_MAKE_FLAGS=-j2'
  - 'export CI_CC=$TRAVIS_COMPILER'
  - 'export CI_MAKEFILES="scripts/makefile.$TRAVIS_COMPILER scripts/makefile.std"'

script:
  - './ci/ci_verify_$AUTOMATION.sh'
